
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up API key
        env:
          SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
        run: |
          echo "api-key=${SPOONACULAR_API_KEY}" >> ./backend/src/test/resources/application.properties
      - name: Build with Maven
        run: mvn -B package --file ./backend/pom.xml